FROM python:3.8.0

LABEL maintainer "Pierrot Julma <pierrot25fr@gmail.com>"

RUN mkdir /mlflow/

COPY modele_LR.pkl e43a1dcf87d3:/home/modele_LR.pkl

RUN pip install mlflow==1.14.0

EXPOSE 5000

CMD mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./artifacts  --host 0.0.0.0

