name: Time-series-jobs

on: [push]

jobs:
  ARIMA:

    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
   
    steps:
    - uses: actions/checkout@v2
    - name: Time-series-ARIMA-model
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Your ML workflow goes here
        pip install -r requirements.txt
        #python pyCode/model.py
        #python pyCode/collect.py
        #python pyCode/eda.py
        #python pyCode/preprocesing.py
        
        python pyCode/model_arima.py        
        
        # Write your CML report
        #echo "## Les Metriques:" >> report.md
        #cat metrics.txt >> report.md
        
        echo "## Les Metriques du modèle arima:" >> report_arima.md
        cat metrics_arima.txt >> report_arima.md       
        
        #echo "## Visualisation des données: " >>report.md
        #cml-publish appleClosePrice.png --md >>report.md
        #cml-publish test_stationarity.png --md >>report.md        
        #cml-publish trainTest.png --md >>report.md        
        #cml-publish applePricePrediction.png --md >>report.md
        
        echo "## Visualisation des données: " >>report_arima.md
        cml-publish priceprediction.png --md >>report_arima.md
        
        #cml-send-comment report.md
        
        cml-send-comment report_arima.md
        
        # read files in the docker container
        ls -l
        
        # move file from container to github repository
        git config --global user.email "pierrot25fr@yahoo.fr"
        git config --global user.name "pjulma"
        git add .
        git commit -m "New file Added"
        git push

  LINEAR:

    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    
    needs: ARIMA
    if: always()
    steps:
    - uses: actions/checkout@v2
    - name: Time-series-linear-regression
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Your ML workflow goes here
        pip install -r requirements.txt
        python pyCode/model_linear.py
        
        # Write your CML report
        echo "## Les Metriques du modèle de regression linéaire:" >> report_linearR.md
        cat metrics_linear.txt >> report_linearR.md
        
        echo "## Visualisation des données: " >>report_linearR.md
        cml-publish LinearPrediction.png --md >>report_linearR.md
         
        
        cml-send-comment report_linearR.md
        
        # move file from container to github repository
        git config --global user.email "pierrot25fr@yahoo.fr"
        git config --global user.name "pjulma"
        git pull
        git add report_linearR.md
        git commit -m "New file Added"
        git push     
  